{{- if eq .osid "linux-arch" -}}
[".local/share/rofi/themes/catppuccin-frappe.rasi"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/rofi/main/basic/.local/share/rofi/themes/catppuccin-frappe.rasi"
refreshPeriod = "672h"

[".local/share/rofi/themes/catppuccin-latte.rasi"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/rofi/main/basic/.local/share/rofi/themes/catppuccin-latte.rasi"
refreshPeriod = "672h"

[".local/share/rofi/themes/catppuccin-macchiato.rasi"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/rofi/main/basic/.local/share/rofi/themes/catppuccin-macchiato.rasi"
refreshPeriod = "672h"

[".local/share/rofi/themes/catppuccin-mocha.rasi"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/rofi/main/basic/.local/share/rofi/themes/catppuccin-mocha.rasi"
refreshPeriod = "672h"
{{- end -}}
