name = 'catppuccin'
flavor = 'latte'

base00 = '#eff1f5' # base
base01 = '#e6e9ef' # mantle
base02 = '#ccd0da' # surface0
base03 = '#bcc0cc' # surface1
base04 = '#acb0be' # surface2
base05 = '#4c4f69' # text
base08 = '#d20f39' # red
base06 = '#dc8a78' # rosewater
base07 = '#7287fd' # lavender
base09 = '#fe640b' # peach
base0A = '#df8e1d' # yellow
base0B = '#40a02b' # green
base0C = '#179299' # teal
base0D = '#1e66f5' # blue
base0E = '#8839ef' # mauve
base0F = '#dd7878' # flamingo

# pink = '#ea76cb'
# maroon = '#e64553'
# sky = '#04a5e5'
# sapphire = '#209fb5'
# subtext1 = '#5c5f77'
# subtext0 = '#6c6f85'
# overlay2 = '#7c7f93'
# overlay1 = '#8c8fa1'
# overlay0 = '#9ca0b0'
# crust = '#dce0e8'
