name = 'catppuccin'
flavor = 'mocha'

base00 = '#1e1e2e' # base
base01 = '#181825' # mantle
base02 = '#313244' # surface0
base03 = '#45475a' # surface1
base04 = '#585b70' # surface2
base05 = '#cdd6f4' # text
base06 = '#f5e0dc' # rosewater
base07 = '#b4befe' # lavender
base08 = '#f38ba8' # red
base09 = '#fab387' # peach
base0A = '#f9e2af' # yellow
base0B = '#a6e3a1' # green
base0C = '#94e2d5' # teal
base0D = '#89b4fa' # blue
base0E = '#cba6f7' # mauve
base0F = '#f2cdcd' # flamingo

# pink = '#f5c2e7'
# maroon = '#eba0ac'
# sky = '#89dceb'
# sapphire = '#74c7ec'
# subtext1 = '#bac2de'
# subtext0 = '#a6adc8'
# overlay2 = '#9399b2'
# overlay1 = '#7f849c'
# overlay0 = '#6c7086'
# crust = '#11111b'
