name = "rosepine"
flavor = "main"

base00 = "191724" # base
base01 = "1f1d2e" # surface
base02 = "26233a" # overlay
base03 = "6e6a86" # muted
base04 = "908caa" # subtle
base05 = "e0def4" # text
base06 = "e0def4" # text
base07 = "524f67" # highlight high
base08 = "eb6f92" # love
base09 = "f6c177" # gold
base0A = "ebbcba" # rose
base0B = "31748f" # pine
base0C = "9ccfd8" # foam
base0D = "c4a7e7" # iris
base0E = "f6c177" # gold
base0F = "524f67" # highlight high
