github.com:
    users:
        punkfairie:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: punkfairie
