#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
"$scripts/launch_waybar" &
"$scripts/tools/dynamic" &

# wallpaper
"$scripts/wall" "$config/wallpapers/cloud.png" &

# effects
"$scripts/rgb" &

# clipboard
copyq --start-server &
clipboard-sync &

# other
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
