[buildPlans.Fairiesevka]
family = "Fairiesevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Fairiesevka.variants]
  inherits = "ss05"

    [buildPlans.Fairiesevka.variants.design]
    capital-a = "curly-serifless"
    capital-b = "more-asymmetric-serifless"
    capital-c = "serifless"
    capital-d = "more-rounded-serifless"
    capital-f = "serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-j = "serifed"
    capital-k = "symmetric-touching-serifless"
    capital-l = "serifless"
    capital-m = "slanted-sides-hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-p = "closed-serifless"
    capital-q = "crossing-baseline"
    capital-r = "standing-serifless"
    capital-s = "serifless"
    capital-u = "toothless-corner-serifless"
    capital-v = "curly-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "curly-serifless-with-crossbar"
    a = "double-storey-toothless-corner"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    e = "rounded"
    f = "serifless"
    g = "double-storey-open"
    h = "tailed-serifless"
    i = "serifed-semi-tailed"
    j = "serifed"
    k = "cursive-serifless"
    m = "tailed-serifless"
    n = "tailed-serifless"
    p = "earless-corner-serifless"
    q = "earless-corner-tailed-serifless"
    r = "compact-serifless"
    t = "flat-hook"
    u = "toothless-corner-serifless"
    v = "curly-serifless"
    w = "straight-vertical-sides-serifless"
    x = "semi-chancery-curly"
    y = "curly-serifless"
    z = "curly-serifless-with-crossbar"
    zero = "oval-slashed"
    one = "no-base"
    two = "curly-neck"
    three = "flat-top"
    four = "semi-open-non-crossing"
    five = "oblique-arched"
    six = "open-contour"
    seven = "bend-serifless-crossbar"
    eight = "crossing-asymmetric"
    nine = "open-contour"
    diacritic-dot = "round"
    punctuation-dot = "round"
    asterisk = "penta-low"
    underscore = "low"
    caret = "medium"
    paren = "large-contour"
    brace = "curly"
    guillemet = "curly"
    number-sign = "slanted"
    ampersand = "et-toothless-corner"
    at = "compact"
    dollar = "open"
    cent = "open"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    question = "smooth"
    pilcrow = "low"
    partial-derivative = "curly-bar"
    micro-sign = "toothless-corner-serifless"
    lig-neq = "more-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"

  [buildPlans.Fairiesevka.ligations]
  inherits = "dlig"

[buildPlans.Fairiesevka.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.Fairiesevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Fairiesevka.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"
