[packages.arch]
archgirlie = [
  "lib32-gamemode",
  "lib32-vkd3d",
  "vkd3d",
  "vulkan-tools",
  "libva-nvidia-driver-git",
  "nvidia",
  "nvidia-settings",
  "xf86-video-nouveau",
]
archbaby = [
  "amd-ucode",
  "libva-mesa-driver",
  "vulkan-radeon",
  "xf86-video-amdgpu",
  "steamlink",
]
